Added a fronted linter
casbin/confita pull request #18
Opened 2022-10-20 14:23 UTC by SunshineZerg

2022-10-21 01:43 UTC, hsluoyz requested changes

2022-10-21 01:43 UTC, hsluoyz commented on web/src/CodeListPage.js
> +              {i18next.t("general:Codes")}&nbsp;&nbsp;&nbsp;&nbsp;
Code

2022-10-21 01:43 UTC, hsluoyz commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Delete it

2022-10-21 01:43 UTC, hsluoyz commented on web/package-lock.json
> +{
Delete it

2022-10-22 18:48 UTC, SunshineZerg commented
Try adding new comment to refresh the pr

2022-10-23 01:21 UTC, closed without merging